services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_USER: bahauddin
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_SSLMODE: disable

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: bahauddin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
